# Base Jekyll configuration

# Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Use _config.build.yml to override these settings on `grunt build`.

name: Japanese Sewing Patterns
url: http://www.japanesesewingpatterns.com
description: Learn to sew Japanese sewing patterns, even if you don't speak Japanese.

author:
  name: Rin Gomura
  email: rin@sewinlove.com.au
  twitter: sewinlove

baseurl: ""
url: "http://www.japanesesewingpatterns.com"

sass:
  style: compact
  sass_dir: _sass

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: date

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

plugins:
  - jekyll-feed

amazon_affilliate_id: 'seinlo-20'
amazon_affilliate_jp_id: 'sewinlove-22'
