backend:
  name: git-gateway
media_folder: "img"
collections:
  - name: "reviews" 
    label: "Review" 
    folder: "_posts/reviews"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "review"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "Review"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", default: [""] }
      - {label: "Tags", name: "tags", widget: "list", default: [""] }
      - {label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {label: "Author", name: "author", widget: "string", default: "" }
      - {label: "Language", name: "language", widget: "string", default: "Japanese"}
      - {label: "Genre", name: "genre", widget: "string", default: "" }
      - {label: "Sizing", name: "sizing", widget: "string", default: "" }
      - {label: "Asin", name: "asin", widget: "string", default: "" }
      - {label: "Total Garments", name: "total-garmets", widget: "string", default: "" }
      - {label: "Garments", name: "garmets", widget: "list", default: [""] }
      - {label: "Body", name: "body", widget: "markdown" }
  - name: "tutorials"
    label: "Tutorials"
    folder: "_posts/tutorials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "review"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "Tutorial"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", default: [""] }
      - {label: "Tags", name: "tags", widget: "list", default: [""] }
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Landscape Image", name: "landscape-image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
    - label: "About Page"
      name: "about"
      file: "about/index.md"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    - label: "Ebook Page"
      name: "ebook"
      file: "ebook/index.md"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    - label: "Privacy Policy"
      name: "privacy-policy"
      file: "privacy-policy/index.md"
      fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
